name: Deploy via FTP

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Criar pasta para adicionar arquivo deploy
      run: mkdir files

    - name: Adicionando arquivos ao zip
      run: zip -r files/deploy.zip .

    - name: Copiar arquivos para servidor
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: files/deploy.zip
        target: public_html/blog/wp-content/themes/